pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Repository cloned successfully'
            }
        }

        stage('List Files') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t simple-site .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker stop simple-site || true
                docker rm simple-site || true
                docker run -d --name simple-site -p 80:80 simple-site
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful'
        }

        failure {
            echo 'Deployment Failed'
        }
    }
}
